### ISSUE TITLE
tool.yaml Metadata Specification

### ISSUE THREAD

**Issue by jmwright** [modelb-llc/dof-helpers#4]
As the tools.yaml file stands right now in [trrs-wssm](https://github.com/modelb-llc/trrs-wssm) project, I'm not sure how to specify that the user needs a 1/2 inch wrench (open or box end). This might be related to the metadata question in #3

**Comment by modelb-jrs** [comment]
Yes, I think it is related to issue #3.  The way I see it, you are describing two separate tools, which include a dimension in their definition, but not their quantity.  Namely,

* 1/2" open end wrench
* 1/2" box end wrench

Then you would have to specify a selected option, noting that any option is viable.  Alternatively you could specify a 1/2" combo wrench and in the notes or instructions comment that the maker may choose to use either end based on preference.

One thing I should do is go back into the assembly instructions template and include some rendering of available options in the parts list for each section.

One of the super convenient aspects of reusing component definition is that using tools in templates and documentation is identical to using parts.  For example, the precautions section of an assembly instructions template can use the same iteration/formatting code to list precautions related to tools (be careful around band saws) and around parts (where protective eye wear when working with acids for etching metals).

The big downside to this plan is it basically commits us to the NodeJS repository proliferation paradigm.

**Comment by jmwright** [comment]
The information above tells me what I needed to know. Thanks!
