### ISSUE TITLE
Where Do Things Like Paint Go?

### ISSUE THREAD

**Issue by jmwright** [modelb-llc/dof-helpers#5]
Is paint a part that goes in part.yaml? It's a consumable that is used across projects with no clear quantity attached to it.

**Comment by modelb-jrs** [comment]
So, one of the things I am learning as we work through real world examples is that modeling OSHW source introduces rigor to the project.  Take a look at [this materials list from the trrs-wssm component](https://github.com/modelb-llc/trrs-wssm/blob/master/dist/assemblyInstructions.adoc#materials-3).  Any consumable material is included in this list.  Solder, super-glue, rubbing alcohol, and cotton balls are all accounted for.  And these are all materials that are used across components and across projects.  

It seems to me this is the only way to enable creating a complete purchase list for a project.  Think of these materials like including staples in a recipe.  You still need to see the amount of flour required so you can check your on hand supplies before you start following the instructions in the recipe.

Regarding paint specifically, both spray paint and brushed paint should include approximate coverage per coat.  So, it should be possible to determine the required volume (+/-) and include that at the quantity/units for the parts entry related to the paint.

**Comment by jmwright** [comment]
This is addressed by the answer above. Closing.
